# ***************************开发配置**************************** #
# 应用版本
version: 0.7.0
# 当前激活的配置名称(请不要修改)
profile: test
# MySQL数据库连接地址
dburl: jdbc:mysql://192.168.9.191:3306/statistic_tool?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
# MySQL数据库用户名
dbuser: platon
# MySQL数据库密码
dbpass: platon
web3j:
  addresses: http://192.168.112.172:6789,http://192.168.112.172:7789
  collect.batch-size: 10
#日志配置
logging:
  file: ./logs/${spring.application.name}-${version}-${profile}.log
  #日志级别
  level:
    org.springframework: error
    com.platon.statistic: debug


