package com.platon.statistic.dao.mapper;

import com.platon.statistic.dao.entity.StaIntegral;
import com.platon.statistic.dao.entity.StaIntegralExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface StaIntegralMapper {
    long countByExample(StaIntegralExample example);

    int deleteByExample(StaIntegralExample example);

    int insert(StaIntegral record);

    int insertSelective(StaIntegral record);

    List<StaIntegral> selectByExample(StaIntegralExample example);

    int updateByExampleSelective(@Param("record") StaIntegral record, @Param("example") StaIntegralExample example);

    int updateByExample(@Param("record") StaIntegral record, @Param("example") StaIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sta_integral
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<StaIntegral> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sta_integral
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<StaIntegral> list, @Param("selective") StaIntegral.Column ... selective);
}