package com.platon.statistic.dao.mapper;

import com.platon.statistic.dao.entity.StaOpt;
import com.platon.statistic.dao.entity.StaOptExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface StaOptMapper {
    long countByExample(StaOptExample example);

    int deleteByExample(StaOptExample example);

    int insert(StaOpt record);

    int insertSelective(StaOpt record);

    List<StaOpt> selectByExample(StaOptExample example);

    int updateByExampleSelective(@Param("record") StaOpt record, @Param("example") StaOptExample example);

    int updateByExample(@Param("record") StaOpt record, @Param("example") StaOptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sta_opt
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<StaOpt> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sta_opt
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<StaOpt> list, @Param("selective") StaOpt.Column ... selective);
}