package com.platon.statistic.dao.mapper;

import com.platon.statistic.dao.entity.StaSign;
import com.platon.statistic.dao.entity.StaSignExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface StaSignMapper {
    long countByExample(StaSignExample example);

    int deleteByExample(StaSignExample example);

    int insert(StaSign record);

    int insertSelective(StaSign record);

    List<StaSign> selectByExample(StaSignExample example);

    int updateByExampleSelective(@Param("record") StaSign record, @Param("example") StaSignExample example);

    int updateByExample(@Param("record") StaSign record, @Param("example") StaSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sta_sign
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<StaSign> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sta_sign
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<StaSign> list, @Param("selective") StaSign.Column ... selective);
}